var AmCharts = {
  "themes": {},
  "maps": {},
  "inheriting": {},
  "charts": {},
  "onReadyArray": {},
  "useUTC": {},
  "updateRate": {},
  "uid": {},
  "lang": {},
  "translations": {},
  "mapTranslations": {},
  "windows": {},
  "initHandlers": {},
  "Class": function () {},
  "addChart": function () {},
  "removeChart": function () {},
  "isModern": {},
  "getIEVersion": function () {},
  "applyLang": function () {},
  "IEversion": {},
  "dx": {},
  "dy": {},
  "isNN": {},
  "isIE": {},
  "chrome": {},
  "handleMouseUp": function () {},
  "handleMouseMove": function () {},
  "handleWheel": function () {},
  "resetMouseOver": function () {},
  "ready": function () {},
  "handleLoad": function () {},
  "addInitHandler": function () {},
  "callInitHandler": function () {},
  "getUniqueId": function () {},
  "clear": function () {},
  "makeChart": function () {},
  "realWrite": function () {},
  "updateCount": {},
  "validateAt": {},
  "update": function () {},
  "bezierX": {},
  "bezierY": {},
  "isReady": {},
  "toBoolean": function () {},
  "removeFromArray": function () {},
  "getPath": function () {},
  "normalizeUrl": function () {},
  "isAbsolute": function () {},
  "isInArray": function () {},
  "getDecimals": function () {},
  "wordwrap": function () {},
  "trim": function () {},
  "wrappedText": function () {},
  "getStyle": function () {},
  "removePx": function () {},
  "getURL": function () {},
  "ifArray": function () {},
  "callMethod": function () {},
  "toNumber": function () {},
  "toColor": function () {},
  "toCoordinate": function () {},
  "fitToBounds": function () {},
  "isDefined": function () {},
  "stripNumbers": function () {},
  "roundTo": function () {},
  "toFixed": function () {},
  "formatDuration": function () {},
  "formatNumber": function () {},
  "addZeroes": function () {},
  "scientificToNormal": function () {},
  "toScientific": function () {},
  "randomColor": function () {},
  "hitTest": function () {},
  "isInRectangle": function () {},
  "isPercents": function () {},
  "formatValue": function () {},
  "formatDataContextValue": function () {},
  "massReplace": function () {},
  "cleanFromEmpty": function () {},
  "addPrefix": function () {},
  "remove": function () {},
  "getEffect": function () {},
  "getObjById": function () {},
  "applyTheme": function () {},
  "isString": function () {},
  "extend": function () {},
  "copyProperties": function () {},
  "processObject": function () {},
  "fixNewLines": function () {},
  "fixBrakes": function () {},
  "deleteObject": function () {},
  "bounce": function () {},
  "easeInOutQuad": function () {},
  "easeInSine": function () {},
  "easeOutSine": function () {},
  "easeOutElastic": function () {},
  "fixStepE": function () {},
  "generateNumber": function () {},
  "setCN": function () {},
  "parseDefs": function () {},
  "AxisBase": function () {},
  "ValueAxis": {
    "base": {}
  },
  "RecAxis": function () {},
  "RecItem": function () {},
  "RecFill": function () {},
  "AmChart": function () {},
  "Slice": function () {},
  "SerialDataItem": function () {},
  "GraphDataItem": function () {},
  "Guide": function () {},
  "Title": function () {},
  "Label": function () {},
  "AmGraph": function () {},
  "ChartCursor": function () {},
  "SimpleChartScrollbar": function () {},
  "ChartScrollbar": {
    "base": {}
  },
  "AmBalloon": function () {},
  "AmCoordinateChart": {
    "base": {}
  },
  "TrendLine": function () {},
  "Image": function () {},
  "circle": function () {},
  "text": function () {},
  "polygon": function () {},
  "rect": function () {},
  "bullet": function () {},
  "triangle": function () {},
  "line": function () {},
  "makeHD": function () {},
  "handDrawnLine": function () {},
  "doNothing": function () {},
  "drop": function () {},
  "wedge": function () {},
  "rgb2hex": function () {},
  "adjustLuminosity": function () {},
  "Bezier": function () {},
  "AmDraw": function () {},
  "AmDObject": function () {},
  "VMLRenderer": function () {},
  "SVGRenderer": function () {},
  "AmLegend": function () {},
  "formatMilliseconds": function () {},
  "extractPeriod": function () {},
  "getDate": function () {},
  "daysInMonth": function () {},
  "newDate": function () {},
  "resetDateToMin": function () {},
  "getPeriodDuration": function () {},
  "intervals": {
    "s": {
      "nextInterval": {},
      "contains": {}
    },
    "ss": {
      "nextInterval": {},
      "contains": {},
      "count": {}
    },
    "mm": {
      "nextInterval": {},
      "contains": {},
      "count": {}
    },
    "hh": {
      "nextInterval": {},
      "contains": {},
      "count": {}
    },
    "DD": {
      "nextInterval": {},
      "contains": {},
      "count": {}
    }
  },
  "getMaxInterval": function () {},
  "dayNames": {},
  "shortDayNames": {},
  "monthNames": {},
  "shortMonthNames": {},
  "getWeekNumber": function () {},
  "stringToDate": function () {},
  "getFromDateString": function () {},
  "formatDate": function () {},
  "changeDate": function () {},
  "changeUTCDate": function () {},
  "AmStockChart": function () {},
  "StockEvent": function () {},
  "DataSet": function () {},
  "PeriodSelector": function () {},
  "StockGraph": {
    "base": {}
  },
  "StockPanel": function () {},
  "CategoryAxesSettings": function () {},
  "ChartCursorSettings": function () {},
  "ChartScrollbarSettings": function () {},
  "LegendSettings": function () {},
  "PanelsSettings": function () {},
  "StockEventsSettings": function () {},
  "ValueAxesSettings": function () {},
  "getItemIndex": function () {},
  "addBr": function () {},
  "applyStyles": function () {},
  "StockLegend": {
    "base": {}
  },
  "DataSetSelector": function () {},
  "StackedBullet": function () {},
  "AmRectangularChart": {
    "base": {}
  },
  "AmSerialChart": {
    "base": {}
  },
  "Cuboid": function () {},
  "CategoryAxis": {
    "base": {}
  }
};
AmCharts.AxisBase.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "zoom": function () {},
  "fixAxisPosition": function () {},
  "init": function () {},
  "draw": function () {},
  "setOrientation": function () {},
  "addTitle": function () {},
  "positionTitle": function () {},
  "pushAxisItem": function () {},
  "handleMouse": function () {},
  "addGuide": function () {},
  "removeGuide": function () {},
  "handleGuideOver": function () {},
  "handleGuideOut": function () {},
  "addEventListeners": function () {},
  "getBBox": function () {},
  "destroy": function () {},
  "chooseMinorFrequency": function () {},
  "parseDatesDraw": function () {},
  "choosePeriod": function () {},
  "getStepWidth": function () {},
  "timeZoom": function () {},
  "minDuration": function () {},
  "checkPeriodChange": function () {},
  "generateDFObject": function () {},
  "hideBalloon": function () {},
  "formatBalloonText": function () {},
  "showBalloon": function () {},
  "adjustBalloonCoordinate": function () {},
  "createBalloon": function () {},
  "setBalloonBounds": function () {}
};
AmCharts.ValueAxis.prototype = {
  "construct": function () {},
  "updateData": function () {},
  "draw": function () {},
  "getDateMinMax": function () {},
  "formatValue": function () {},
  "getMinorGridStep": function () {},
  "stackGraphs": function () {},
  "recalculate": function () {},
  "getMinMax": function () {},
  "getExtremes": function () {},
  "zoomOut": function () {},
  "zoomToRelativeValues": function () {},
  "zoomToValues": function () {},
  "coordinateToValue": function () {},
  "getCoordinate": function () {},
  "synchronizeWithAxis": function () {},
  "handleSynchronization": function () {},
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "zoom": function () {},
  "fixAxisPosition": function () {},
  "init": function () {},
  "setOrientation": function () {},
  "addTitle": function () {},
  "positionTitle": function () {},
  "pushAxisItem": function () {},
  "handleMouse": function () {},
  "addGuide": function () {},
  "removeGuide": function () {},
  "handleGuideOver": function () {},
  "handleGuideOut": function () {},
  "addEventListeners": function () {},
  "getBBox": function () {},
  "destroy": function () {},
  "chooseMinorFrequency": function () {},
  "parseDatesDraw": function () {},
  "choosePeriod": function () {},
  "getStepWidth": function () {},
  "timeZoom": function () {},
  "minDuration": function () {},
  "checkPeriodChange": function () {},
  "generateDFObject": function () {},
  "hideBalloon": function () {},
  "formatBalloonText": function () {},
  "showBalloon": function () {},
  "adjustBalloonCoordinate": function () {},
  "createBalloon": function () {},
  "setBalloonBounds": function () {}
};
AmCharts.RecAxis.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.RecItem.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "graphics": function () {},
  "getLabel": function () {}
};
AmCharts.RecFill.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "graphics": function () {},
  "getLabel": function () {}
};
AmCharts.AmChart.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "drawChart": function () {},
  "drawBackground": function () {},
  "drawTitles": function () {},
  "write": function () {},
  "afterWrite": function () {},
  "createLabelsSet": function () {},
  "initChart": function () {},
  "premeasure": function () {},
  "measure": function () {},
  "checkDisplay": function () {},
  "destroy": function () {},
  "clearTimeOuts": function () {},
  "clear": function () {},
  "setMouseCursor": function () {},
  "redrawLabels": function () {},
  "drawLabel": function () {},
  "addLabel": function () {},
  "clearLabels": function () {},
  "updateHeight": function () {},
  "updateWidth": function () {},
  "getTitleHeight": function () {},
  "addTitle": function () {},
  "handleWheel": function () {},
  "handleWheelReal": function () {},
  "handleDocTouchStart": function () {},
  "handleDocTouchEnd": function () {},
  "addListeners": function () {},
  "dispDUpd": function () {},
  "validateSize": function () {},
  "invalidateSize": function () {},
  "invalidateSizeReal": function () {},
  "validateData": function () {},
  "validateNow": function () {},
  "showItem": function () {},
  "hideItem": function () {},
  "hideBalloon": function () {},
  "cleanChart": function () {},
  "hideBalloonReal": function () {},
  "showBalloon": function () {},
  "showBalloonReal": function () {},
  "handleMouseOver": function () {},
  "handleMouseOut": function () {},
  "handleMouseOutReal": function () {},
  "handleMouseMove": function () {},
  "handleTouchStart": function () {},
  "handleTouchEnd": function () {},
  "handleReleaseOutside": function () {},
  "handleMouseDown": function () {},
  "addLegend": function () {},
  "removeLegend": function () {},
  "handleResize": function () {},
  "renderFix": function () {},
  "getSVG": function () {},
  "animate": function () {},
  "setLegendData": function () {},
  "stopAnim": function () {},
  "updateAnimations": function () {},
  "update": function () {},
  "inIframe": function () {},
  "brr": function () {}
};
AmCharts.Slice.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.SerialDataItem.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.GraphDataItem.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.Guide.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.Title.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.Label.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.AmGraph.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "init": function () {},
  "draw": function () {},
  "createGraph": function () {},
  "setAnimationPlayed": function () {},
  "createXYGraph": function () {},
  "createRadarGraph": function () {},
  "positionLabel": function () {},
  "getGradRotation": function () {},
  "createSerialGraph": function () {},
  "animateColumns": function () {},
  "createLabel": function () {},
  "positiveClip": function () {},
  "negativeClip": function () {},
  "drawLineGraph": function () {},
  "applyMask": function () {},
  "drawSmoothedGraph": function () {},
  "launchAnimation": function () {},
  "animateGraphs": function () {},
  "animate": function () {},
  "legendKeyColor": function () {},
  "legendKeyAlpha": function () {},
  "createBullet": function () {},
  "showBullets": function () {},
  "hideBullets": function () {},
  "showCustomBullets": function () {},
  "hideCustomBullets": function () {},
  "addListeners": function () {},
  "handleRollOver": function () {},
  "handleRollOut": function () {},
  "handleClick": function () {},
  "handleGraphEvent": function () {},
  "handleRightClick": function () {},
  "handleDoubleClick": function () {},
  "zoom": function () {},
  "changeOpacity": function () {},
  "destroy": function () {},
  "createBalloon": function () {},
  "hideBalloon": function () {},
  "hideBalloonReal": function () {},
  "fixBulletSize": function () {},
  "showGraphBalloon": function () {},
  "resizeBullet": function () {}
};
AmCharts.ChartCursor.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "draw": function () {},
  "createElements": function () {},
  "update": function () {},
  "updateDrawing": function () {},
  "fixWidth": function () {},
  "fixHeight": function () {},
  "fixVLine": function () {},
  "fixHLine": function () {},
  "hideCursor": function () {},
  "hideLines": function () {},
  "showCursor": function () {},
  "updateFullLine": function () {},
  "updateSelection": function () {},
  "mouseIsOver": function () {},
  "fixPosition": function () {},
  "handleMouseDown": function () {},
  "registerInitialMouse": function () {},
  "handleReleaseOutside": function () {},
  "dispatchZoomEvent": function () {},
  "dispatchMovedEvent": function () {},
  "dispatchPanEvent": function () {},
  "clearSelection": function () {},
  "destroy": function () {},
  "clear": function () {},
  "setTimestamp": function () {},
  "setIndex": function () {},
  "handleMouseOut": function () {},
  "showCursorAt": function () {},
  "setPosition": function () {},
  "enableDrawing": function () {},
  "syncWithCursor": function () {},
  "isZooming": function () {},
  "syncWithCursorReal": function () {}
};
AmCharts.SimpleChartScrollbar.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "draw": function () {},
  "updateScrollbarSize": function () {},
  "update": function () {},
  "stopForceClip": function () {},
  "clipDragger": function () {},
  "maskGraphs": function () {},
  "clipAndUpdate": function () {},
  "dispatchScrollbarEvent": function () {},
  "updateDragIconPositions": function () {},
  "showDragIcons": function () {},
  "hideDragIcons": function () {},
  "removeCursors": function () {},
  "fireZoomEvent": function () {},
  "percentZoom": function () {},
  "destroy": function () {},
  "clear": function () {},
  "handleDragStart": function () {},
  "handleDragStop": function () {},
  "handleDraggerOver": function () {},
  "leftDragStart": function () {},
  "leftDragStop": function () {},
  "rightDragStart": function () {},
  "rightDragStop": function () {},
  "iconRollOut": function () {},
  "iconRollOver": function () {},
  "getDBox": function () {},
  "handleBgClick": function () {},
  "updateOnRelease": function () {},
  "handleReleaseOutside": function () {},
  "handleMouseOver": function () {},
  "handleMouseOut": function () {}
};
AmCharts.ChartScrollbar.prototype = {
  "construct": function () {},
  "init": function () {},
  "draw": function () {},
  "timeZoom": function () {},
  "zoom": function () {},
  "dispatchScrollbarEvent": function () {},
  "zoomScrollbar": function () {},
  "maskGraphs": function () {},
  "handleDragStart": function () {},
  "handleBackgroundClick": function () {},
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "updateScrollbarSize": function () {},
  "update": function () {},
  "stopForceClip": function () {},
  "clipDragger": function () {},
  "clipAndUpdate": function () {},
  "updateDragIconPositions": function () {},
  "showDragIcons": function () {},
  "hideDragIcons": function () {},
  "removeCursors": function () {},
  "fireZoomEvent": function () {},
  "percentZoom": function () {},
  "destroy": function () {},
  "clear": function () {},
  "handleDragStop": function () {},
  "handleDraggerOver": function () {},
  "leftDragStart": function () {},
  "leftDragStop": function () {},
  "rightDragStart": function () {},
  "rightDragStop": function () {},
  "iconRollOut": function () {},
  "iconRollOver": function () {},
  "getDBox": function () {},
  "handleBgClick": function () {},
  "updateOnRelease": function () {},
  "handleReleaseOutside": function () {},
  "handleMouseOver": function () {},
  "handleMouseOut": function () {}
};
AmCharts.AmBalloon.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "draw": function () {},
  "fixPrevious": function () {},
  "restorePrevious": function () {},
  "followMouse": function () {},
  "changeColor": function () {},
  "setBounds": function () {},
  "showBalloon": function () {},
  "hide": function () {},
  "setPosition": function () {},
  "followCursor": function () {},
  "removeDiv": function () {},
  "destroy": function () {}
};
AmCharts.AmCoordinateChart.prototype = {
  "construct": function () {},
  "initChart": function () {},
  "createValueAxes": function () {},
  "parseData": function () {},
  "parseSerialData": function () {},
  "delayParseSerialData": function () {},
  "parsePartSerialData": function () {},
  "processValues": function () {},
  "parseGraphData": function () {},
  "addValueAxis": function () {},
  "removeValueAxesAndGraphs": function () {},
  "removeValueAxis": function () {},
  "addGraph": function () {},
  "removeGraph": function () {},
  "handleValueAxisZoom": function () {},
  "processValueAxes": function () {},
  "processGuides": function () {},
  "processGraphs": function () {},
  "formatString": function () {},
  "getBalloonColor": function () {},
  "getGraphById": function () {},
  "getValueAxisById": function () {},
  "processFields": function () {},
  "chooseGraphColor": function () {},
  "handleLegendEvent": function () {},
  "highlightGraph": function () {},
  "unhighlightGraph": function () {},
  "showGraph": function () {},
  "hideGraph": function () {},
  "hideGraphsBalloon": function () {},
  "showGraphsBalloon": function () {},
  "updateLegend": function () {},
  "resetAnimation": function () {},
  "animateAgain": function () {},
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "drawChart": function () {},
  "drawBackground": function () {},
  "drawTitles": function () {},
  "write": function () {},
  "afterWrite": function () {},
  "createLabelsSet": function () {},
  "premeasure": function () {},
  "measure": function () {},
  "checkDisplay": function () {},
  "destroy": function () {},
  "clearTimeOuts": function () {},
  "clear": function () {},
  "setMouseCursor": function () {},
  "redrawLabels": function () {},
  "drawLabel": function () {},
  "addLabel": function () {},
  "clearLabels": function () {},
  "updateHeight": function () {},
  "updateWidth": function () {},
  "getTitleHeight": function () {},
  "addTitle": function () {},
  "handleWheel": function () {},
  "handleWheelReal": function () {},
  "handleDocTouchStart": function () {},
  "handleDocTouchEnd": function () {},
  "addListeners": function () {},
  "dispDUpd": function () {},
  "validateSize": function () {},
  "invalidateSize": function () {},
  "invalidateSizeReal": function () {},
  "validateData": function () {},
  "validateNow": function () {},
  "showItem": function () {},
  "hideItem": function () {},
  "hideBalloon": function () {},
  "cleanChart": function () {},
  "hideBalloonReal": function () {},
  "showBalloon": function () {},
  "showBalloonReal": function () {},
  "handleMouseOver": function () {},
  "handleMouseOut": function () {},
  "handleMouseOutReal": function () {},
  "handleMouseMove": function () {},
  "handleTouchStart": function () {},
  "handleTouchEnd": function () {},
  "handleReleaseOutside": function () {},
  "handleMouseDown": function () {},
  "addLegend": function () {},
  "removeLegend": function () {},
  "handleResize": function () {},
  "renderFix": function () {},
  "getSVG": function () {},
  "animate": function () {},
  "setLegendData": function () {},
  "stopAnim": function () {},
  "updateAnimations": function () {},
  "update": function () {},
  "inIframe": function () {},
  "brr": function () {}
};
AmCharts.TrendLine.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "draw": function () {},
  "handleLineClick": function () {},
  "handleLineOver": function () {},
  "handleLineOut": function () {},
  "destroy": function () {}
};
AmCharts.Image.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "draw": function () {},
  "translate": function () {}
};
AmCharts.Bezier.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "interpolate": function () {},
  "drawBeziers": function () {},
  "drawBezierMidpoint": function () {},
  "getMiddle": function () {},
  "getPointOnSegment": function () {}
};
AmCharts.AmDraw.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "createSvgElement": function () {},
  "circle": function () {},
  "ellipse": function () {},
  "setSize": function () {},
  "rect": function () {},
  "image": function () {},
  "addToContainer": function () {},
  "text": function () {},
  "path": function () {},
  "set": function () {},
  "remove": function () {},
  "renderFix": function () {},
  "update": function () {},
  "addDefs": function () {}
};
AmCharts.AmDObject.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "attr": function () {},
  "getAttr": function () {},
  "setAttr": function () {},
  "clipRect": function () {},
  "translate": function () {},
  "rotate": function () {},
  "animate": function () {},
  "push": function () {},
  "text": function () {},
  "remove": function () {},
  "clear": function () {},
  "hide": function () {},
  "show": function () {},
  "getBBox": function () {},
  "toFront": function () {},
  "toPrevious": function () {},
  "toBack": function () {},
  "mouseover": function () {},
  "mouseout": function () {},
  "click": function () {},
  "dblclick": function () {},
  "mousedown": function () {},
  "mouseup": function () {},
  "touchmove": function () {},
  "touchstart": function () {},
  "touchend": function () {},
  "contextmenu": function () {},
  "stop": function () {},
  "length": function () {},
  "gradient": function () {},
  "pattern": function () {}
};
AmCharts.VMLRenderer.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "create": function () {},
  "path": function () {},
  "setAttr": function () {},
  "attr": function () {},
  "text": function () {},
  "getBBox": function () {},
  "getBox": function () {},
  "setText": function () {},
  "move": function () {},
  "svgPathToVml": function () {},
  "animate": function () {},
  "clipRect": function () {},
  "rotate": function () {},
  "getBGColor": function () {},
  "set": function () {},
  "gradient": function () {},
  "remove": function () {},
  "disableSelection": function () {},
  "pattern": function () {},
  "update": function () {}
};
AmCharts.SVGRenderer.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "create": function () {},
  "attr": function () {},
  "setAttr": function () {},
  "animate": function () {},
  "update": function () {},
  "getBBox": function () {},
  "path": function () {},
  "clipRect": function () {},
  "text": function () {},
  "setText": function () {},
  "move": function () {},
  "rotate": function () {},
  "set": function () {},
  "gradient": function () {},
  "removeTarget": function () {},
  "pattern": function () {},
  "remove": function () {}
};
AmCharts.AmLegend.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "setData": function () {},
  "invalidateSize": function () {},
  "drawLegend": function () {},
  "arrangeEntries": function () {},
  "createEntry": function () {},
  "addListeners": function () {},
  "rollOverMarker": function () {},
  "rollOutMarker": function () {},
  "clickMarker": function () {},
  "rollOverLabel": function () {},
  "rollOutLabel": function () {},
  "clickLabel": function () {},
  "dispatch": function () {},
  "createValue": function () {},
  "createV": function () {},
  "createX": function () {},
  "createMarker": function () {},
  "validateNow": function () {},
  "updateValues": function () {},
  "renderFix": function () {},
  "destroy": function () {}
};
AmCharts.AmStockChart.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "write": function () {},
  "afterWrite": function () {},
  "setDefaultPeriod": function () {},
  "validateSize": function () {},
  "updateDataSets": function () {},
  "getLastDate": function () {},
  "getFirstDate": function () {},
  "updateData": function () {},
  "fixGlue": function () {},
  "isDataParsed": function () {},
  "onDataUpdated": function () {},
  "updateComparingData": function () {},
  "delayedParseStockData": function () {},
  "parseStockData": function () {},
  "parseEvents": function () {},
  "getEventDataItem": function () {},
  "createLayout": function () {},
  "addPanels": function () {},
  "measurePanels": function () {},
  "addStockPanel": function () {},
  "enableCursors": function () {},
  "updatePanels": function () {},
  "updatePanel": function () {},
  "zoom": function () {},
  "zoomOut": function () {},
  "updatePanelsWithNewData": function () {},
  "addChartScrollbar": function () {},
  "handleScrollbarZoom": function () {},
  "addPeriodSelector": function () {},
  "addDataSetSelector": function () {},
  "handlePeriodSelectorZoom": function () {},
  "zoomOutValueAxes": function () {},
  "addCursor": function () {},
  "handleCursorChange": function () {},
  "handleCursorZoom": function () {},
  "handleZoom": function () {},
  "zoomChart": function () {},
  "dispDUpd": function () {},
  "resetSkip": function () {},
  "updateGraphs": function () {},
  "passFields": function () {},
  "choosePeriod": function () {},
  "getSelections": function () {},
  "addPanel": function () {},
  "addPanelAt": function () {},
  "removePanel": function () {},
  "validateData": function () {},
  "validateDataReal": function () {},
  "resetDataParsed": function () {},
  "validateNow": function () {},
  "hideStockEvents": function () {},
  "showStockEvents": function () {},
  "showHideEvents": function () {},
  "invalidateSize": function () {},
  "measure": function () {},
  "handleResize": function () {},
  "validateSizeReal": function () {},
  "clear": function () {}
};
AmCharts.StockEvent.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.DataSet.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.PeriodSelector.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "zoom": function () {},
  "write": function () {},
  "addEventListeners": function () {},
  "getPeriodDates": function () {},
  "handleCalendarChange": function () {},
  "handleCalChange": function () {},
  "handlePeriodChange": function () {},
  "setRanges": function () {},
  "selectPeriodButton": function () {},
  "markButtonAsSelected": function () {},
  "unselectButtons": function () {},
  "setDefaultPeriod": function () {}
};
AmCharts.StockGraph.prototype = {
  "construct": function () {},
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "init": function () {},
  "draw": function () {},
  "createGraph": function () {},
  "setAnimationPlayed": function () {},
  "createXYGraph": function () {},
  "createRadarGraph": function () {},
  "positionLabel": function () {},
  "getGradRotation": function () {},
  "createSerialGraph": function () {},
  "animateColumns": function () {},
  "createLabel": function () {},
  "positiveClip": function () {},
  "negativeClip": function () {},
  "drawLineGraph": function () {},
  "applyMask": function () {},
  "drawSmoothedGraph": function () {},
  "launchAnimation": function () {},
  "animateGraphs": function () {},
  "animate": function () {},
  "legendKeyColor": function () {},
  "legendKeyAlpha": function () {},
  "createBullet": function () {},
  "showBullets": function () {},
  "hideBullets": function () {},
  "showCustomBullets": function () {},
  "hideCustomBullets": function () {},
  "addListeners": function () {},
  "handleRollOver": function () {},
  "handleRollOut": function () {},
  "handleClick": function () {},
  "handleGraphEvent": function () {},
  "handleRightClick": function () {},
  "handleDoubleClick": function () {},
  "zoom": function () {},
  "changeOpacity": function () {},
  "destroy": function () {},
  "createBalloon": function () {},
  "hideBalloon": function () {},
  "hideBalloonReal": function () {},
  "fixBulletSize": function () {},
  "showGraphBalloon": function () {},
  "resizeBullet": function () {}
};
AmCharts.StockPanel.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "inherits": function () {},
  "construct": function () {},
  "initChart": function () {},
  "addStockGraph": function () {},
  "handleCursorZoom": function () {},
  "removeStockGraph": function () {},
  "createDrawIcons": function () {},
  "handlePencilClick": function () {},
  "disableDrawing": function () {},
  "handleEraserClick": function () {},
  "setTrendColorHover": function () {},
  "handleDraw": function () {},
  "hideDrawingIcons": function () {},
  "handleTrendClick": function () {},
  "handleWheelReal": function () {}
};
AmCharts.CategoryAxesSettings.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.ChartCursorSettings.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "categoryBalloonDateFormat": function () {}
};
AmCharts.ChartScrollbarSettings.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.LegendSettings.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.PanelsSettings.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.StockEventsSettings.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.ValueAxesSettings.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {}
};
AmCharts.StockLegend.prototype = {
  "construct": function () {},
  "drawLegend": function () {},
  "handleXOver": function () {},
  "handleXOut": function () {},
  "handleXClick": function () {},
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "setData": function () {},
  "invalidateSize": function () {},
  "arrangeEntries": function () {},
  "createEntry": function () {},
  "addListeners": function () {},
  "rollOverMarker": function () {},
  "rollOutMarker": function () {},
  "clickMarker": function () {},
  "rollOverLabel": function () {},
  "rollOutLabel": function () {},
  "clickLabel": function () {},
  "dispatch": function () {},
  "createValue": function () {},
  "createV": function () {},
  "createX": function () {},
  "createMarker": function () {},
  "validateNow": function () {},
  "updateValues": function () {},
  "renderFix": function () {},
  "destroy": function () {}
};
AmCharts.DataSetSelector.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "write": function () {},
  "addEventListeners": function () {},
  "handleDataSetChange": function () {},
  "handleRollOver": function () {},
  "handleRollOut": function () {},
  "handleCBSelect": function () {},
  "handleClick": function () {},
  "getRealDiv": function () {},
  "countDataSets": function () {}
};
AmCharts.StackedBullet.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "parseConfig": function () {},
  "write": function () {},
  "addLetter": function () {},
  "addEventListeners": function () {},
  "drawPin": function () {},
  "drawSign": function () {},
  "drawFlag": function () {},
  "drawTriangleUp": function () {},
  "drawArrowUp": function () {},
  "drawArrowDown": function () {},
  "drawTriangleDown": function () {},
  "drawTriangleLeft": function () {},
  "drawTriangleRight": function () {},
  "drawRealPolygon": function () {},
  "drawCircle": function () {},
  "drawTextBackground": function () {},
  "handleMouseOver": function () {},
  "handleClick": function () {},
  "handleMouseOut": function () {}
};
AmCharts.AmRectangularChart.prototype = {
  "construct": function () {},
  "initChart": function () {},
  "drawChart": function () {},
  "resetMargins": function () {},
  "measureMargins": function () {},
  "getAxisBounds": function () {},
  "drawZoomOutButton": function () {},
  "rollOverZB": function () {},
  "rollOutZB": function () {},
  "clickZB": function () {},
  "zoomOut": function () {},
  "drawPlotArea": function () {},
  "updatePlotArea": function () {},
  "updateDxy": function () {},
  "updateMargins": function () {},
  "updateValueAxes": function () {},
  "setAxisRenderers": function () {},
  "updateGraphs": function () {},
  "updateObjectSize": function () {},
  "updateChartCursor": function () {},
  "processScrollbars": function () {},
  "updateScrollbars": function () {},
  "removeChartCursor": function () {},
  "zoomTrendLines": function () {},
  "handleCursorValueZoom": function () {},
  "addTrendLine": function () {},
  "zoomOutValueAxes": function () {},
  "removeTrendLine": function () {},
  "adjustMargins": function () {},
  "getScrollbarPosition": function () {},
  "updateChartScrollbar": function () {},
  "showZB": function () {},
  "handleReleaseOutside": function () {},
  "handleMouseDown": function () {},
  "update": function () {},
  "handleScrollbarValueZoom": function () {},
  "zoomValueScrollbar": function () {},
  "zoomAxesAndGraphs": function () {},
  "handleValueAxisZoomReal": function () {},
  "updateAfterValueZoom": function () {},
  "relativeZoomValueAxes": function () {},
  "addChartCursor": function () {},
  "handleCursorChange": function () {},
  "handleCursorMove": function () {},
  "handleCursorZoom": function () {},
  "handleCursorHide": function () {},
  "createValueAxes": function () {},
  "parseData": function () {},
  "parseSerialData": function () {},
  "delayParseSerialData": function () {},
  "parsePartSerialData": function () {},
  "processValues": function () {},
  "parseGraphData": function () {},
  "addValueAxis": function () {},
  "removeValueAxesAndGraphs": function () {},
  "removeValueAxis": function () {},
  "addGraph": function () {},
  "removeGraph": function () {},
  "handleValueAxisZoom": function () {},
  "processValueAxes": function () {},
  "processGuides": function () {},
  "processGraphs": function () {},
  "formatString": function () {},
  "getBalloonColor": function () {},
  "getGraphById": function () {},
  "getValueAxisById": function () {},
  "processFields": function () {},
  "chooseGraphColor": function () {},
  "handleLegendEvent": function () {},
  "highlightGraph": function () {},
  "unhighlightGraph": function () {},
  "showGraph": function () {},
  "hideGraph": function () {},
  "hideGraphsBalloon": function () {},
  "showGraphsBalloon": function () {},
  "updateLegend": function () {},
  "resetAnimation": function () {},
  "animateAgain": function () {},
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "drawBackground": function () {},
  "drawTitles": function () {},
  "write": function () {},
  "afterWrite": function () {},
  "createLabelsSet": function () {},
  "premeasure": function () {},
  "measure": function () {},
  "checkDisplay": function () {},
  "destroy": function () {},
  "clearTimeOuts": function () {},
  "clear": function () {},
  "setMouseCursor": function () {},
  "redrawLabels": function () {},
  "drawLabel": function () {},
  "addLabel": function () {},
  "clearLabels": function () {},
  "updateHeight": function () {},
  "updateWidth": function () {},
  "getTitleHeight": function () {},
  "addTitle": function () {},
  "handleWheel": function () {},
  "handleWheelReal": function () {},
  "handleDocTouchStart": function () {},
  "handleDocTouchEnd": function () {},
  "addListeners": function () {},
  "dispDUpd": function () {},
  "validateSize": function () {},
  "invalidateSize": function () {},
  "invalidateSizeReal": function () {},
  "validateData": function () {},
  "validateNow": function () {},
  "showItem": function () {},
  "hideItem": function () {},
  "hideBalloon": function () {},
  "cleanChart": function () {},
  "hideBalloonReal": function () {},
  "showBalloon": function () {},
  "showBalloonReal": function () {},
  "handleMouseOver": function () {},
  "handleMouseOut": function () {},
  "handleMouseOutReal": function () {},
  "handleMouseMove": function () {},
  "handleTouchStart": function () {},
  "handleTouchEnd": function () {},
  "addLegend": function () {},
  "removeLegend": function () {},
  "handleResize": function () {},
  "renderFix": function () {},
  "getSVG": function () {},
  "animate": function () {},
  "setLegendData": function () {},
  "stopAnim": function () {},
  "updateAnimations": function () {},
  "inIframe": function () {},
  "brr": function () {}
};
AmCharts.AmSerialChart.prototype = {
  "construct": function () {},
  "initChart": function () {},
  "onDataUpdated": function () {},
  "handleWheelReal": function () {},
  "validateData": function () {},
  "drawChart": function () {},
  "cleanChart": function () {},
  "updateCategoryAxis": function () {},
  "updateValueAxes": function () {},
  "getStartTime": function () {},
  "getEndTime": function () {},
  "updateMargins": function () {},
  "updateScrollbars": function () {},
  "zoom": function () {},
  "timeZoom": function () {},
  "showZB": function () {},
  "updateAfterValueZoom": function () {},
  "indexZoom": function () {},
  "updateGraphs": function () {},
  "zoomAxesAndGraphs": function () {},
  "updateColumnsDepth": function () {},
  "compareDepth": function () {},
  "zoomScrollbar": function () {},
  "updateTrendLines": function () {},
  "countColumns": function () {},
  "parseData": function () {},
  "getCategoryIndexByValue": function () {},
  "handleScrollbarZoom": function () {},
  "dispatchTimeZoomEvent": function () {},
  "dispatchIndexZoomEvent": function () {},
  "updateLegendValues": function () {},
  "getClosestIndex": function () {},
  "zoomToIndexes": function () {},
  "zoomToDates": function () {},
  "zoomToCategoryValues": function () {},
  "formatPeriodString": function () {},
  "formatString": function () {},
  "updateChartCursor": function () {},
  "addChartScrollbar": function () {},
  "addValueScrollbar": function () {},
  "removeChartScrollbar": function () {},
  "removeValueScrollbar": function () {},
  "handleReleaseOutside": function () {},
  "update": function () {},
  "processScrollbars": function () {},
  "handleValueAxisZoom": function () {},
  "zoomOut": function () {},
  "getNextItem": function () {},
  "handleCursorZoomReal": function () {},
  "handleCursorZoomStarted": function () {},
  "fixCursor": function () {},
  "handleCursorMove": function () {},
  "handleCursorHide": function () {},
  "handleCursorPanning": function () {},
  "arrangeBalloons": function () {},
  "compareY": function () {},
  "resetMargins": function () {},
  "measureMargins": function () {},
  "getAxisBounds": function () {},
  "drawZoomOutButton": function () {},
  "rollOverZB": function () {},
  "rollOutZB": function () {},
  "clickZB": function () {},
  "drawPlotArea": function () {},
  "updatePlotArea": function () {},
  "updateDxy": function () {},
  "setAxisRenderers": function () {},
  "updateObjectSize": function () {},
  "removeChartCursor": function () {},
  "zoomTrendLines": function () {},
  "handleCursorValueZoom": function () {},
  "addTrendLine": function () {},
  "zoomOutValueAxes": function () {},
  "removeTrendLine": function () {},
  "adjustMargins": function () {},
  "getScrollbarPosition": function () {},
  "updateChartScrollbar": function () {},
  "handleMouseDown": function () {},
  "handleScrollbarValueZoom": function () {},
  "zoomValueScrollbar": function () {},
  "handleValueAxisZoomReal": function () {},
  "relativeZoomValueAxes": function () {},
  "addChartCursor": function () {},
  "handleCursorChange": function () {},
  "handleCursorZoom": function () {},
  "createValueAxes": function () {},
  "parseSerialData": function () {},
  "delayParseSerialData": function () {},
  "parsePartSerialData": function () {},
  "processValues": function () {},
  "parseGraphData": function () {},
  "addValueAxis": function () {},
  "removeValueAxesAndGraphs": function () {},
  "removeValueAxis": function () {},
  "addGraph": function () {},
  "removeGraph": function () {},
  "processValueAxes": function () {},
  "processGuides": function () {},
  "processGraphs": function () {},
  "getBalloonColor": function () {},
  "getGraphById": function () {},
  "getValueAxisById": function () {},
  "processFields": function () {},
  "chooseGraphColor": function () {},
  "handleLegendEvent": function () {},
  "highlightGraph": function () {},
  "unhighlightGraph": function () {},
  "showGraph": function () {},
  "hideGraph": function () {},
  "hideGraphsBalloon": function () {},
  "showGraphsBalloon": function () {},
  "updateLegend": function () {},
  "resetAnimation": function () {},
  "animateAgain": function () {},
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "drawBackground": function () {},
  "drawTitles": function () {},
  "write": function () {},
  "afterWrite": function () {},
  "createLabelsSet": function () {},
  "premeasure": function () {},
  "measure": function () {},
  "checkDisplay": function () {},
  "destroy": function () {},
  "clearTimeOuts": function () {},
  "clear": function () {},
  "setMouseCursor": function () {},
  "redrawLabels": function () {},
  "drawLabel": function () {},
  "addLabel": function () {},
  "clearLabels": function () {},
  "updateHeight": function () {},
  "updateWidth": function () {},
  "getTitleHeight": function () {},
  "addTitle": function () {},
  "handleWheel": function () {},
  "handleDocTouchStart": function () {},
  "handleDocTouchEnd": function () {},
  "addListeners": function () {},
  "dispDUpd": function () {},
  "validateSize": function () {},
  "invalidateSize": function () {},
  "invalidateSizeReal": function () {},
  "validateNow": function () {},
  "showItem": function () {},
  "hideItem": function () {},
  "hideBalloon": function () {},
  "hideBalloonReal": function () {},
  "showBalloon": function () {},
  "showBalloonReal": function () {},
  "handleMouseOver": function () {},
  "handleMouseOut": function () {},
  "handleMouseOutReal": function () {},
  "handleMouseMove": function () {},
  "handleTouchStart": function () {},
  "handleTouchEnd": function () {},
  "addLegend": function () {},
  "removeLegend": function () {},
  "handleResize": function () {},
  "renderFix": function () {},
  "getSVG": function () {},
  "animate": function () {},
  "setLegendData": function () {},
  "stopAnim": function () {},
  "updateAnimations": function () {},
  "inIframe": function () {},
  "brr": function () {}
};
AmCharts.Cuboid.prototype = {
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "construct": function () {},
  "draw": function () {},
  "width": function () {},
  "height": function () {},
  "animateHeight": function () {},
  "updateHeight": function () {},
  "animateWidth": function () {},
  "updateWidth": function () {}
};
AmCharts.CategoryAxis.prototype = {
  "construct": function () {},
  "draw": function () {},
  "xToIndex": function () {},
  "dateToCoordinate": function () {},
  "categoryToCoordinate": function () {},
  "coordinateToDate": function () {},
  "coordinateToValue": function () {},
  "getCoordinate": function () {},
  "formatValue": function () {},
  "showBalloonAt": function () {},
  "formatBalloonText": function () {},
  "adjustBalloonCoordinate": function () {},
  "createEvents": function () {},
  "listenTo": function () {},
  "addListener": function () {},
  "removeListener": function () {},
  "fire": function () {},
  "zoom": function () {},
  "fixAxisPosition": function () {},
  "init": function () {},
  "setOrientation": function () {},
  "addTitle": function () {},
  "positionTitle": function () {},
  "pushAxisItem": function () {},
  "handleMouse": function () {},
  "addGuide": function () {},
  "removeGuide": function () {},
  "handleGuideOver": function () {},
  "handleGuideOut": function () {},
  "addEventListeners": function () {},
  "getBBox": function () {},
  "destroy": function () {},
  "chooseMinorFrequency": function () {},
  "parseDatesDraw": function () {},
  "choosePeriod": function () {},
  "getStepWidth": function () {},
  "timeZoom": function () {},
  "minDuration": function () {},
  "checkPeriodChange": function () {},
  "generateDFObject": function () {},
  "hideBalloon": function () {},
  "showBalloon": function () {},
  "createBalloon": function () {},
  "setBalloonBounds": function () {}
};

